# fanfictionloader ffd-retief
application: fanfictionloader
version: 4-0-1
runtime: python
api_version: 1

handlers:
- url: /r3m0v3r.*
  script: utils/remover.py
  login: admin

- url: /fdownloadtask
  script: main.py
  login: admin
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
