# ffd-retief-hrd fanfictiondownloader
application: fanfictiondownloader
version: 4-4-11
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /r3m0v3r.*
  script: utils.remover.app
  login: admin

- url: /tally.*
  script: utils.tally.app
  login: admin

- url: /fdownloadtask
  script: main.app
  login: admin
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: main.app

#builtins:
#- datastore_admin: on

libraries:
- name: django
  version: "1.2"

- name: PIL
  version: "1.1.7"
